---
site_name: ansible-kovacs
site_author: Mael & Micka
copyright: Copyright &copy; 2026 Mael & Micka
repo_url: https://github.com/saiqo/ansible-kovacs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: deep-purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep-purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Rubik
  language: fr

  # favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes

plugins:
  - search:
      lang: fr


markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html



# extra:
#   social:
#     - icon: fontawesome/brands/github 
#       link: https://github.com/saiqo

nav:
  - Rapports Ansible:
    - Index: index.md
    - Tests: tests/index.md
    - Atelier 01 - Installation d'ansible: 01-Installation_ansible/index.md
    - Atelier 03 - Authentification: 03-Authentification/index.md
    - Atelier 06 - Configuration de base: 06-Configuration_de_base/index.md
    - Atelier 07 - Idempotence: 07-Idempotence/index.md
    - Atelier 10 - Playbooks: 10-Playbooks/index.md
    - Atelier 12 - Handlers: 12-Handlers/index.md
    - Atelier 14 - Variables: 14-Variables/index.md
    - Atelier 15 - Variables Enregistrés: 15-Variables-Enregistrés/index.md
    - Atelier 16 - Facts et variables implicites: 16-Facts-et-variables-implicites/index.md
    - Atelier 17 - Cibles Hétérogènes: 17-Cibles-Heterogenes/index.md

  - Commandes utiles: commandes_utiles.md
